import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./Components/NavBar";
import { Playfair_Display, Open_Sans } from 'next/font/google'
import OpenTableSection from "./Components/OpenTableSection";
import { Footer } from "./Components/Footer";


const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair',
})

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-opensans',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfair.variable} ${openSans.variable}`}>
      <body 
      >
        <NavBar />
        {children}
        <OpenTableSection />
        <Footer />
      </body>
    </html>
  );
}
